### ISSUE TITLE
Problem için örnek çözümler ortaya çıkar 

### ISSUE THREAD

**Issue by onuryilmaz** [onuryilmaz/thesis-v1#4]

**Comment by cornetto** [comment]
Step 4: 
Bu aşamada structural özellikler ve mismatch pattern'lardan ortaya çıkan "properties" ile performans verilerinden çıkan "KPI" lar arasında bağlantı kurmaya çalışacağım.

**Comment by cornetto** [comment]
Step 4:
- Cluster logs according to performance values (waiting time, utilization, etc)
- Find mismatch patterns between clusters

Step 5:
- Provide suggestions based on mismatch patterns

**Comment by cornetto** [comment]
* Step 1: Partition Logs
* Step 2: Mine with for Each Organization and Align Models
* Step 3: Replay Logs and Calculate Performance Indicators
* Step 4: Learn with Configuration and Performance
  *  Cluster logs according to performance values (waiting time, utilization, etc)
  * Find mismatch patterns between clusters
* Step 5: Provide Suggestions

**Comment by cornetto** [comment]
Log'ları replay ederek her uzunluktaki average, minimum, maximum ve std sürelerini hesapladım.
Bu süreleri kullanarak R üzerinde clustering yapıp test klasörü altında ilk çıktıları toparladım.

- [x] Step 1: Partition Logs
- [x] Step 2: Mine with for Each Organization and Align Models
- [x] Step 3: Replay Logs and Calculate Performance Indicators
- [ ] Step 4: Learn with Configuration and Performance
- Cluster logs according to performance values (waiting time, utilization, etc) 
- Find mismatch patterns between clusters
Step 5: Provide Suggestions

**Comment by cornetto** [comment]
Gerçek hayattan log'lar ile yukarıdaki adımları tekrar et.
Ayrıca zaman dışındaki variable'ları da sisteme eklemeye çalış

**Comment by cornetto** [comment]
Business concept'i olan log'lar ile yukarıdaki adımlar tekrar edildi -> [Loan Application](test/loan)
Gerçek hayattan log'lar ile ileride denecek.

**Comment by cornetto** [comment]
Real life event ile denendi, benzer sonuçlar alınıyor.
Denenen loglar CoSeLoG projesinden: http://www.win.tue.nl/coselog/wiki/start
Dataset: http://data.3tu.nl/repository/uuid:26aba40d-8b2d-435b-b5af-6d4bfbd7a270
